version: '3'
services:
  pleo-antaeus:
    build: .
    ports:
     - "8000:8000"
    environment:
      - PAYMENT_PROVIDER_ENDPOINT=http://pleo-payment:8080
  pleo-payment:
    build: solution/app
    ports:
      - 8080:8080
